MERGE INTO SAP_ZMM023_GERAL tgt
USING STG_SAP_ZMM023 src
ON (
    tgt.DOCUMENTO_COMPRAS = src.DOCUMENTO_COMPRAS AND
    tgt.ITEM = src.ITEM AND
    tgt.REQUISICAO_COMPRA = src.REQUISICAO_COMPRA AND
    tgt.ITEM_REQUISICAO = src.ITEM_REQUISICAO
)
WHEN MATCHED THEN
    UPDATE SET
        tgt.NOME_DA_FIRMA = src.NOME_DA_FIRMA,
        tgt.GRUPO_DE_COMPRADORES = src.GRUPO_DE_COMPRADORES,
        tgt.TIPO_DOCUMENTO_COMPRAS = src.TIPO_DOCUMENTO_COMPRAS,
        tgt.MATERIAL = src.MATERIAL,
        tgt.TEXTO_BREVE = src.TEXTO_BREVE,
        tgt.GRUPO_MERCADORIAS = src.GRUPO_MERCADORIAS,
        tgt.DENOM_GRUPO_MERCADORIAS = src.DENOM_GRUPO_MERCADORIAS,
        tgt.QTD_PEDIDO = src.QTD_PEDIDO,
        tgt.UM_PEDIDO = src.UM_PEDIDO,
        tgt.NUM_ACOMPANHAMENTO = src.NUM_ACOMPANHAMENTO,
        tgt.PRECO_LIQ_PEDIDO = src.PRECO_LIQ_PEDIDO,
        tgt.MOEDA = src.MOEDA,
        tgt.VALOR_LIQUIDO_PEDIDO = src.VALOR_LIQUIDO_PEDIDO,
        tgt.CAMBIO_PEDIDO_REAIS = src.CAMBIO_PEDIDO_REAIS,
        tgt.FORNECEDOR = src.FORNECEDOR,
        tgt.NOME_FORNECEDOR = src.NOME_FORNECEDOR,
        tgt.DATA_CRIACAO = src.DATA_CRIACAO,
        tgt.DATA_SOLICITACAO = src.DATA_SOLICITACAO,
        tgt.DATA_LANCAMENTO = src.DATA_LANCAMENTO,
        tgt.TIPO_FORNECEDOR = src.TIPO_FORNECEDOR,
        tgt.ORCAMENTO = src.ORCAMENTO,
        tgt.CENTRO_CUSTO = src.CENTRO_CUSTO,
        tgt.APLICACAO = src.APLICACAO

WHEN NOT MATCHED THEN
    INSERT (
        NOME_DA_FIRMA,
        GRUPO_DE_COMPRADORES,
        TIPO_DOCUMENTO_COMPRAS,
        DOCUMENTO_COMPRAS,
        ITEM,
        MATERIAL,
        TEXTO_BREVE,
        GRUPO_MERCADORIAS,
        DENOM_GRUPO_MERCADORIAS,
        QTD_PEDIDO,
        UM_PEDIDO,
        REQUISICAO_COMPRA,
        ITEM_REQUISICAO,
        NUM_ACOMPANHAMENTO,
        PRECO_LIQ_PEDIDO,
        MOEDA,
        VALOR_LIQUIDO_PEDIDO,
        CAMBIO_PEDIDO_REAIS,
        FORNECEDOR,
        NOME_FORNECEDOR,
        DATA_CRIACAO,
        DATA_SOLICITACAO,
        DATA_LANCAMENTO,
        TIPO_FORNECEDOR,
        ORCAMENTO,
        CENTRO_CUSTO,
        APLICACAO
    )
    VALUES (
        src.NOME_DA_FIRMA,
        src.GRUPO_DE_COMPRADORES,
        src.TIPO_DOCUMENTO_COMPRAS,
        src.DOCUMENTO_COMPRAS,
        src.ITEM,
        src.MATERIAL,
        src.TEXTO_BREVE,
        src.GRUPO_MERCADORIAS,
        src.DENOM_GRUPO_MERCADORIAS,
        src.QTD_PEDIDO,
        src.UM_PEDIDO,
        src.REQUISICAO_COMPRA,
        src.ITEM_REQUISICAO,
        src.NUM_ACOMPANHAMENTO,
        src.PRECO_LIQ_PEDIDO,
        src.MOEDA,
        src.VALOR_LIQUIDO_PEDIDO,
        src.CAMBIO_PEDIDO_REAIS,
        src.FORNECEDOR,
        src.NOME_FORNECEDOR,
        src.DATA_CRIACAO,
        src.DATA_SOLICITACAO,
        src.DATA_LANCAMENTO,
        src.TIPO_FORNECEDOR,
        src.ORCAMENTO,
        src.CENTRO_CUSTO,
        src.APLICACAO
    )

